server:
  port: 8443

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8081}/eureka/

spring:
  application:
    name: geteway
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
  security:
    oauth2:
      jwt:
        signingKey: 123456
  cloud:
    gateway:
      locator:
        enabled: true
      default-filters:
      - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      routes:
      # =====================================
      - id: producer
        uri: lb://producer
        order: 8000
        predicates:
        - Path=/product/**
        filters:
        - StripPrefix=2
      - id: oauth2
        uri: lb://oauth2
        order: 8000
        predicates:
        - Path=/oauth2/**
        filters:
        - StripPrefix=2
gate:
  ignore:
    authentication:
      startWith: /oauth,/open

management:
  endpoints:
    web:
      exposure:
        include: '*'

#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true

#  compression:
#    response:
#      enabled: true
#    request:
#      enabled: true
#      mime-types: text/xml,application/xml,application/json
#      min-request-size: 2048
hystrix:
  command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 3000
logging:
  level:
    com.springboot.cloud.gateway: debug
    com.jalja.org.spring.simple.dao.FeignUserClient: DEBUG
  path: logs/
  file:
    max-size: 1GB