server:
  port: ${SERVER_PORT:8443}

spring:
  application:
    name: ${GATEWAY_NAME:gateway-web}

  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    #password: ${REDIS_PASSWORD:}

  zipkin:
    enabled: true
    sender:
      type: rabbit
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
  #jwt密码
  security:
    oauth2:
      jwt:
        signingKey: 123456
  cloud:
    nacos:
      discovery:
        server-addr: ${REGISTER_HOST:localhost}:${REGISTER_PORT:8848}
    gateway:
      default-filters:
      - name: Retry
        args:
          retries: 3
          statuses: BAD_GATEWAY
      - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      - name: RequestRateLimiter
        args:
          redis-rate-limiter.replenishRate: 2  #流速 每秒
          redis-rate-limiter.burstCapacity: 10   #令牌桶的容积
          rate-limiter: "#{@defaultRedisRateLimiter}"  #SPEL表达式去的对应的bean
          key-resolver: "#{@apiKeyResolver}" #SPEL表达式去的对应的bean

#网关白名单，无需要签权url
gate:
  ignore:
    authentication:
      startWith: /oauth,/open,/v2/api-docs

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.springboot.cloud.gateway: debug
    com.jalja.org.spring: debug
  path: logs/
  file:
    max-size: 1GB