spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启服务发现
          lower-case-service-id: true  # 服务ID小写
      default-filters:
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY
            methods: GET,POST
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 2  #流速 每秒
            redis-rate-limiter.burstCapacity: 10   #令牌桶的容积
            rate-limiter: "#{@defaultRedisRateLimiter}"  #SPEL表达式去的对应的bean
            key-resolver: "#{@apiKeyResolver}" #SPEL表达式去的对应的bean

#网关白名单，无需要签权url
gate:
  ignore:
    authentication:
      startWith: /oauth,/open,/v2/api-docs